version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_LISTENER_NAMES: INSIDE,OUTSIDE
      KAFKA_LISTENER_INTERNAL_PORT: 9093
      KAFKA_LISTENER_EXTERNAL_PORT: 9092
      KAFKA_LISTENER_INTERNAL_HOST_NAME: kafka
      KAFKA_LISTENER_EXTERNAL_HOST_NAME: localhost
      KAFKA_LISTENER_INTERNAL_LISTENER: INSIDE
      KAFKA_LISTENER_EXTERNAL_LISTENER: OUTSIDE
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
      - "9093:9093"
