server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: product-service
          uri: http://localhost:8081
          predicates:
            - Path=/produits/**

        - id: customer-service
          uri: http://localhost:8082
          predicates:
            - Path=/customers/**
